engines:
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCasePropertyName:
        allow-underscore: true
ratings:
  paths:
  - "**.php"
  - "**.module"
  - "**.inc"
exclude_paths:
- tests/**/*
