language: php

# list any PHP version you want to test against
php:
  - 5.4
  - 5.5
  - 5.6

composer install

# omitting "script:" will default to phpunit
script: phpunit --configuration test/phpunit.xml --coverage-text
